### ISSUE TITLE
Overriding key names

### ISSUE THREAD

**Issue by queil** [vanwinkelseppe/serilog-enrichers-kubernetes#6]
Hi @vanwinkelseppe, thanks for this nice Serilog extension. I've just set it up and it works great. However, I'd like more control over key names and possible overriding it via configuration. Is this something you were considering implementing? Or do you accept PRs otherwise?

**Comment by queil** [comment]
Ok, I actually didn't use in the end. Thanks anyway.

**Comment by vanwinkelseppe** [comment]
Hi @queil 

Thanks for the suggestions. I have added the suggestion in the latest version.

Greetings
